name: Enable UptimeRobot Monitor

on:
  schedule:
    - cron: '0 21 * * *' # 台灣時間 05:00（UTC+8 = UTC 21:00 前一天）
  workflow_dispatch:  # 可手動執行

jobs:
  enable-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Enable monitor via UptimeRobot API
        run: |
          curl -X POST https://api.uptimerobot.com/v2/editMonitor \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "api_key=${{ secrets.UPTIMEROBOT_API_KEY }}" \
            -d "id=${{ secrets.UPTIMEROBOT_MONITOR_ID }}" \
            -d "status=1"
