name: Ping Render Server

on:
  schedule:
    - cron: '0 21 * * *'
    - cron: '12 21 * * *'
    - cron: '24 21 * * *'
    - cron: '36 21 * * *'
    - cron: '48 21 * * *'
    - cron: '0 22 * * *'
    - cron: '12 22 * * *'
    - cron: '24 22 * * *'
    - cron: '36 22 * * *'
    - cron: '48 22 * * *'
    - cron: '0 23 * * *'
    - cron: '12 23 * * *'
    - cron: '24 23 * * *'
    - cron: '36 23 * * *'
    - cron: '48 23 * * *'
    - cron: '0 0 * * *'
    - cron: '12 0 * * *'
    - cron: '24 0 * * *'
    - cron: '36 0 * * *'
    - cron: '48 0 * * *'
    - cron: '0 1 * * *'
    - cron: '12 1 * * *'
    - cron: '24 1 * * *'
    - cron: '36 1 * * *'
    - cron: '48 1 * * *'
    - cron: '0 2 * * *'
    - cron: '12 2 * * *'
    - cron: '24 2 * * *'
    - cron: '36 2 * * *'
    - cron: '48 2 * * *'
    - cron: '0 3 * * *'
    - cron: '12 3 * * *'
    - cron: '24 3 * * *'
    - cron: '36 3 * * *'
    - cron: '48 3 * * *'
    - cron: '0 4 * * *'
    - cron: '12 4 * * *'
    - cron: '24 4 * * *'
    - cron: '36 4 * * *'
    - cron: '48 4 * * *'
    - cron: '0 5 * * *'
    - cron: '12 5 * * *'
    - cron: '24 5 * * *'
    - cron: '36 5 * * *'
    - cron: '48 5 * * *'
    - cron: '0 6 * * *'
    - cron: '12 6 * * *'
    - cron: '24 6 * * *'
    - cron: '36 6 * * *'
    - cron: '48 6 * * *'
    - cron: '0 7 * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: curl -s https://newsbeiter.onrender.com/healthcheck
